name: 'Qodana Scan'
uses: JetBrains/qodana-action@main
env:
  QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
on:
  push:
    branches:
      - '*'


jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.3.0


